[2020-04-17 13:49:58,952] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atvt_inferencing.at_gateway_inference_task 2020-04-17T04:46:00+00:00 [queued]>
[2020-04-17 13:49:58,959] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atvt_inferencing.at_gateway_inference_task 2020-04-17T04:46:00+00:00 [queued]>
[2020-04-17 13:49:58,959] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-04-17 13:49:58,959] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-04-17 13:49:58,959] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-04-17 13:49:59,042] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): at_gateway_inference_task> on 2020-04-17T04:46:00+00:00
[2020-04-17 13:49:59,053] {standard_task_runner.py:53} INFO - Started process 26936 to run task
[2020-04-17 13:49:59,279] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: atvt_inferencing.at_gateway_inference_task 2020-04-17T04:46:00+00:00 [running]> bi02.com
[2020-04-17 13:50:19,252] {taskinstance.py:1128} ERROR - unsupported operand type(s) for +: 'float' and 'str'
Traceback (most recent call last):
  File "/home/chkimsu/anaconda3/envs/csb2/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/chkimsu/anaconda3/envs/csb2/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/chkimsu/anaconda3/envs/csb2/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/data01/CSB/CSB_Jupyter/ATVT/ariflow/dags/.ipynb_checkpoints/Inferencing_airflow-module-checkpoint.py", line 165, in at_gateway_inference_task
    file.writelines(line+'\n')
TypeError: unsupported operand type(s) for +: 'float' and 'str'
[2020-04-17 13:50:19,253] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=atvt_inferencing, task_id=at_gateway_inference_task, execution_date=20200417T044600, start_date=20200417T044958, end_date=20200417T045019
[2020-04-17 13:50:19,600] {logging_mixin.py:112} INFO - [2020-04-17 13:50:19,600] {local_task_job.py:167} WARNING - State of this instance has been externally set to failed. Taking the poison pill.
[2020-04-17 13:50:19,612] {helpers.py:322} INFO - Sending Signals.SIGTERM to GPID 26936
[2020-04-17 13:50:19,619] {helpers.py:288} INFO - Process psutil.Process(pid=26936, status='terminated') (26936) terminated with exit code 1
[2020-04-17 13:50:24,599] {logging_mixin.py:112} INFO - [2020-04-17 13:50:24,598] {local_task_job.py:103} INFO - Task exited with return code 1
