[2020-04-17 17:31:52,265] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atvt_inferencing.at_gateway_inference_task 2020-04-17T08:28:00+00:00 [queued]>
[2020-04-17 17:31:52,271] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: atvt_inferencing.at_gateway_inference_task 2020-04-17T08:28:00+00:00 [queued]>
[2020-04-17 17:31:52,271] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-04-17 17:31:52,271] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-04-17 17:31:52,272] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-04-17 17:31:52,352] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): at_gateway_inference_task> on 2020-04-17T08:28:00+00:00
[2020-04-17 17:31:52,362] {standard_task_runner.py:53} INFO - Started process 63156 to run task
[2020-04-17 17:31:52,498] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: atvt_inferencing.at_gateway_inference_task 2020-04-17T08:28:00+00:00 [running]> bi02.com
[2020-04-17 17:32:11,738] {python_operator.py:114} INFO - Done. Returned value was: Fail
[2020-04-17 17:32:12,147] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=atvt_inferencing, task_id=at_gateway_inference_task, execution_date=20200417T082800, start_date=20200417T083152, end_date=20200417T083212
[2020-04-17 17:32:13,207] {logging_mixin.py:112} INFO - [2020-04-17 17:32:13,206] {local_task_job.py:103} INFO - Task exited with return code 0
